image: Visual Studio 2017

environment:
  matrix:
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32
      PYTHON: python3
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32
      PYTHON: python2
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      PYTHON: python3
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      PYTHON: python2

init:
  - set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%

build_script:
  - set CHERE_INVOKING=yes
  - cd %APPVEYOR_BUILD_FOLDER%
  - bash -lc "bash -x test-msys2-pre.sh"
  - bash -lc "bash -x test-msys2.sh"

deploy: off

test: off
