_defaults_osx: &defaults_osx
  os: osx
  osx_image: xcode8.3
  language: generic

matrix:
  include:
    - env: PYTHON="python2"
      <<: *defaults_osx
    - env: PYTHON="python3"
      <<: *defaults_osx

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bash -x test-osx.sh; fi
